## **Psychology assisted academic performance**

Importing all the libraries

---

In [ ]:
# NumPy is used to perform mathematical operations on arrays.
import numpy as np
# matplotlib. pyplot is a collection of functions that make matplotlib work like MATLAB like creates a figure, creates a plotting area in a figure etc.
import matplotlib.pyplot as plt
# Pandas is mainly used for data analysis. It helps in importing data from various file types such as csv, Json, Microsoft excel, etc. 
import pandas as pd
# extends the list of mathematical functions.
import math

Connecting to drive to get the dataset saved earlier...

---

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Education_data_ML_34.csv')

In [ ]:
# The head() function is used to get the first n rows.
df.head()

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,15,16,2,20,Yes,Good,Under-7,M
1,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,20,20,3,25,Yes,Good,Under-7,M
2,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,10,7,0,30,No,Bad,Above-7,L
3,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,30,25,5,35,No,Bad,Above-7,L
4,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,40,50,12,50,No,Bad,Above-7,M

In [ ]:
df #dataframe

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,15,16,2,20,Yes,Good,Under-7,M
1,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,20,20,3,25,Yes,Good,Under-7,M
2,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,10,7,0,30,No,Bad,Above-7,L
3,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,30,25,5,35,No,Bad,Above-7,L
4,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,40,50,12,50,No,Bad,Above-7,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,F,Jordan,Jordan,MiddleSchool,G-08,A,Chemistry,S,Father,5,4,5,8,No,Bad,Above-7,L
476,F,Jordan,Jordan,MiddleSchool,G-08,A,Geology,F,Father,50,77,14,28,No,Bad,Under-7,M
477,F,Jordan,Jordan,MiddleSchool,G-08,A,Geology,S,Father,55,74,25,29,No,Bad,Under-7,M
478,F,Jordan,Jordan,MiddleSchool,G-08,A,History,F,Father,30,17,14,57,No,Bad,Above-7,L
479,F,Jordan,Jordan,MiddleSchool,G-08,A,History,S,Father,35,14,23,62,No,Bad,Above-7,L

In [ ]:
# Only selecting columns based on Pyschology
cols = ['raisedhands',	'VisITedResources',	'AnnouncementsView',	'Discussion', 'Class']
df = df[cols]
df.head()

   raisedhands  VisITedResources  AnnouncementsView  Discussion Class
0           15                16                  2          20     M
1           20                20                  3          25     M
2           10                 7                  0          30     L
3           30                25                  5          35     L
4           40                50                 12          50     M

In [ ]:
num_neighbors = 5

# **KNN Algorithm implementation**

In [ ]:
training=df.values[0:479,0:4]
training

array([[15, 16, 2, 20],
       [20, 20, 3, 25],
       [10, 7, 0, 30],
       ...,
       [50, 77, 14, 28],
       [55, 74, 25, 29],
       [30, 17, 14, 57]], dtype=object)

In [ ]:
trainingclass=df.values[0:479,-1]
trainingclass

array(['M', 'M', 'L', 'L', 'M', 'M', 'L', 'M', 'M', 'M', 'H', 'M', 'L',
       'L', 'H', 'M', 'M', 'M', 'M', 'H', 'M', 'M', 'M', 'L', 'L', 'L',
       'M', 'L', 'M', 'M', 'H', 'L', 'L', 'L', 'L', 'L', 'L', 'M', 'L',
       'M', 'L', 'M', 'L', 'M', 'M', 'L', 'L', 'H', 'H', 'M', 'L', 'L',
       'M', 'H', 'L', 'L', 'L', 'L', 'M', 'M', 'L', 'M', 'H', 'M', 'L',
       'L', 'M', 'H', 'H', 'M', 'L', 'M', 'L', 'M', 'L', 'M', 'M', 'M',
       'L', 'H', 'L', 'L', 'L', 'M', 'H', 'L', 'H', 'L', 'L', 'L', 'L',
       'H', 'H', 'H', 'L', 'H', 'H', 'M', 'M', 'M', 'M', 'H', 'L', 'L',
       'M', 'L', 'M', 'H', 'M', 'M', 'H', 'M', 'L', 'L', 'L', 'L', 'M',
       'H', 'M', 'M', 'M', 'L', 'M', 'M', 'L', 'L', 'M', 'L', 'L', 'L',
       'L', 'M', 'L', 'L', 'H', 'H', 'H', 'M', 'H', 'M', 'L', 'L', 'M',
       'H', 'L', 'M', 'H', 'M', 'M', 'H', 'H', 'M', 'H', 'L', 'M', 'H',
       'M', 'M', 'L', 'M', 'H', 'M', 'H', 'M', 'M', 'H', 'M', 'H', 'H',
       'M', 'H', 'M', 'L', 'L', 'M', 'L', 'H', 'M', 'H', 'M', 'H', 'L',
       'H', 'M', 'L', 'H', 'M', 'M', 'H', 'M', 'L', 'L', 'M', 'M', 'M',
       'M', 'H', 'H', 'L', 'M', 'H', 'H', 'M', 'M', 'L', 'H', 'M', 'M',
       'M', 'M', 'H', 'M', 'H', 'L', 'L', 'L', 'M', 'M', 'H', 'M', 'M',
       'M', 'M', 'H', 'H', 'M', 'L', 'L', 'H', 'L', 'M', 'L', 'M', 'M',
       'M', 'L', 'L', 'M', 'M', 'H', 'H', 'M', 'L', 'M', 'H', 'M', 'H',
       'M', 'L', 'M', 'H', 'L', 'M', 'L', 'H', 'H', 'H', 'M', 'M', 'L',
       'L', 'M', 'M', 'M', 'M', 'H', 'M', 'M', 'M', 'M', 'H', 'M', 'M',
       'H', 'H', 'H', 'H', 'H', 'M', 'M', 'H', 'H', 'H', 'H', 'M', 'M',
       'H', 'H', 'M', 'M', 'L', 'L', 'H', 'H', 'M', 'M', 'H', 'H', 'M',
       'M', 'L', 'L', 'M', 'M', 'M', 'M', 'H', 'H', 'M', 'M', 'M', 'M',
       'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'M', 'M', 'L', 'L', 'M',
       'M', 'L', 'L', 'M', 'M', 'L', 'L', 'M', 'M', 'L', 'L', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'H', 'H', 'H', 'H', 'L', 'L', 'L',
       'L', 'M', 'M', 'H', 'H', 'M', 'M', 'H', 'H', 'M', 'M', 'H', 'H',
       'H', 'H', 'M', 'M', 'H', 'H', 'M', 'M', 'L', 'L', 'L', 'L', 'M',
       'M', 'L', 'L', 'L', 'L', 'H', 'H', 'H', 'H', 'M', 'M', 'L', 'L',
       'M', 'M', 'H', 'H', 'H', 'H', 'M', 'M', 'H', 'H', 'M', 'M', 'H',
       'H', 'H', 'H', 'L', 'L', 'M', 'M', 'H', 'H', 'M', 'M', 'L', 'L',
       'H', 'H', 'H', 'H', 'H', 'H', 'M', 'M', 'H', 'H', 'M', 'M', 'L',
       'L', 'H', 'H', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'L', 'L', 'M', 'M', 'H', 'H', 'H', 'H', 'M', 'M', 'M',
       'M', 'H', 'H', 'H', 'H', 'M', 'M', 'M', 'M', 'H', 'H', 'H', 'H',
       'L', 'L', 'M', 'M', 'M', 'M', 'L', 'L', 'M', 'M', 'L'],
      dtype=object)

In [ ]:
def euclidean_distance(row1, row2):
	distance = 0.0
	for i in range(len(row1)-1):
		distance += (row1[i] - row2[i])**2
	return (math.sqrt(distance))

In [ ]:
testing=df.values[479,0:4]
testing

array([35, 14, 23, 62], dtype=object)

In [ ]:
unique_list=[]
for x in trainingclass:
  if x not in unique_list:
    unique_list.append(x)

print(unique_list)
for i in range(len(trainingclass)):
  for k in range(len(unique_list)):
    if(trainingclass[i]==unique_list[k]):
      trainingclass[i]=k
print(trainingclass)

['M', 'L', 'H']
[0 0 1 1 0 0 1 0 0 0 2 0 1 1 2 0 0 0 0 2 0 0 0 1 1 1 0 1 0 0 2 1 1 1 1 1 1
 0 1 0 1 0 1 0 0 1 1 2 2 0 1 1 0 2 1 1 1 1 0 0 1 0 2 0 1 1 0 2 2 0 1 0 1 0
 1 0 0 0 1 2 1 1 1 0 2 1 2 1 1 1 1 2 2 2 1 2 2 0 0 0 0 2 1 1 0 1 0 2 0 0 2
 0 1 1 1 1 0 2 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 2 2 2 0 2 0 1 1 0 2 1 0 2 0
 0 2 2 0 2 1 0 2 0 0 1 0 2 0 2 0 0 2 0 2 2 0 2 0 1 1 0 1 2 0 2 0 2 1 2 0 1
 2 0 0 2 0 1 1 0 0 0 0 2 2 1 0 2 2 0 0 1 2 0 0 0 0 2 0 2 1 1 1 0 0 2 0 0 0
 0 2 2 0 1 1 2 1 0 1 0 0 0 1 1 0 0 2 2 0 1 0 2 0 2 0 1 0 2 1 0 1 2 2 2 0 0
 1 1 0 0 0 0 2 0 0 0 0 2 0 0 2 2 2 2 2 0 0 2 2 2 2 0 0 2 2 0 0 1 1 2 2 0 0
 2 2 0 0 1 1 0 0 0 0 2 2 0 0 0 0 2 2 2 2 2 2 2 2 0 0 1 1 0 0 1 1 0 0 1 1 0
 0 1 1 0 0 0 0 0 0 0 0 2 2 2 2 1 1 1 1 0 0 2 2 0 0 2 2 0 0 2 2 2 2 0 0 2 2
 0 0 1 1 1 1 0 0 1 1 1 1 2 2 2 2 0 0 1 1 0 0 2 2 2 2 0 0 2 2 0 0 2 2 2 2 1
 1 0 0 2 2 0 0 1 1 2 2 2 2 2 2 0 0 2 2 0 0 1 1 2 2 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 0 0 2 2 2 2 0 0 0 0 2 2 2 2 0 0 0 0 2 2 2 2 1 1 0 0 0 0 1 1 0 0 1]

In [ ]:
distance=[]
for i in range(len(training)):
  distance.append([euclidean_distance((training[i]),(testing)),trainingclass[i]])

distance

[[29.068883707497267, 0],
 [25.709920264364882, 0],
 [34.68429039204925, 1],
 [21.6794833886788, 1],
 [37.97367509209505, 0],
 [20.12461179749811, 0],
 [23.08679276123039, 1],
 [17.46424919657298, 0],
 [25.03996805109783, 0],
 [74.73285756613352, 0],
 [75.82875444051551, 2],
 [18.33030277982336, 0],
 [39.97499218261337, 1],
 [18.601075237738275, 1],
 [65.62011886609167, 2],
 [26.49528259898354, 0],
 [16.30950643030009, 0],
 [23.345235059857504, 0],
 [36.41428291206625, 0],
 [53.009433122794285, 2],
 [53.301031884945715, 0],
 [31.464265445104548, 0],
 [29.832867780352597, 0],
 [41.54515615568198, 1],
 [42.05948168962618, 1],
 [28.75760768909681, 1],
 [16.881943016134134, 0],
 [14.89966442575134, 1],
 [86.49855490122364, 0],
 [76.81796664843453, 0],
 [71.30918594402827, 2],
 [36.4828726939094, 1],
 [35.81898937714463, 1],
 [31.448370387032774, 1],
 [27.622454633866266, 1],
 [25.787593916455254, 1],
 [33.97057550292606, 1],
 [41.340053217188775, 0],
 [44.15880433163923, 1],
 [78.7210264160726, 0],
 [29.017236257093817, 1],
 [18.466185312619388, 0],
 [29.748949561287034, 1],
 [22.15851980616034, 0],
 [20.346989949375804, 0],
 [17.11724276862369, 1],
 [35.832945734337834, 1],
 [39.761790704142086, 2],
 [71.61703707917552, 2],
 [37.282703764614496, 0],
 [18.601075237738275, 1],
 [8.12403840463596, 1],
 [78.8986691902975, 0],
 [57.86190456595773, 2],
 [45.27692569068709, 1],
 [25.495097567963924, 1],
 [26.419689627245813, 1],
 [36.51027252705737, 1],
 [46.70117771534247, 0],
 [11.357816691600547, 0],
 [15.394804318340652, 1],
 [58.66856057549052, 0],
 [100.0499875062461, 2],
 [19.339079605813716, 0],
 [39.52214569073901, 1],
 [24.289915602982237, 1],
 [11.489125293076057, 0],
 [67.97793759742936, 2],
 [66.2872536767062, 2],
 [28.91366458960192, 0],
 [24.372115213907882, 1],
 [17.204650534085253, 0],
 [34.07345007480164, 1],
 [22.825424421026653, 0],
 [31.843366656181317, 1],
 [77.69813382572325, 0],
 [61.09009739720506, 0],
 [68.4178339323893, 0],
 [27.367864366808018, 1],
 [92.07062506576133, 2],
 [29.9833287011299, 1],
 [36.52396473549935, 1],
 [36.138621999185304, 1],
 [32.449961479175904, 0],
 [63.953107821277925, 2],
 [42.8485705712571, 1],
 [38.961519477556315, 2],
 [61.57921727336261, 1],
 [37.26929030716845, 1],
 [37.68288736283355, 1],
 [34.14674215792775, 1],
 [93.94147114027967, 2],
 [58.111960903070546, 2],
 [79.46068210127572, 2],
 [55.39855593785816, 1],
 [94.98420921395304, 2],
 [51.97114584074513, 2],
 [34.785054261852174, 0],
 [35.70714214271425, 0],
 [21.6794833886788, 0],
 [79.30952023559341, 0],
 [89.65489389877163, 2],
 [39.92492955535426, 1],
 [38.65229618017538, 1],
 [40.36087214122113, 0],
 [41.773197148410844, 1],
 [30.479501308256342, 0],
 [85.58621384311844, 2],
 [33.34666400106613, 0],
 [78.80355321938218, 0],
 [87.89197915623473, 2],
 [83.09031231136396, 0],
 [39.6232255123179, 1],
 [28.24889378365107, 1],
 [35.34119409414458, 1],
 [37.48332962798263, 1],
 [79.0, 0],
 [24.779023386727733, 2],
 [23.706539182259394, 0],
 [56.04462507680822, 0],
 [27.0, 0],
 [39.370039370059054, 1],
 [88.09653795694811, 0],
 [92.39588735436226, 0],
 [40.620192023179804, 1],
 [36.24913792078372, 1],
 [37.013511046643494, 0],
 [32.4037034920393, 1],
 [23.53720459187964, 1],
 [86.2670273047588, 1],
 [33.66006535941367, 1],
 [53.08483775994799, 0],
 [38.92300091205713, 1],
 [56.3382640840131, 1],
 [80.2807573457052, 2],
 [103.75451797391764, 2],
 [103.75451797391764, 2],
 [75.56454194925024, 0],
 [117.32433677630571, 2],
 [114.49890829173874, 0],
 [55.362442142665635, 1],
 [59.88321968631947, 1],
 [73.28028384224504, 0],
 [93.94147114027967, 2],
 [26.551836094703507, 1],
 [77.26577508832743, 0],
 [93.13968005098579, 2],
 [69.99285677838846, 0],
 [48.52834223420371, 0],
 [93.13968005098579, 2],
 [84.64632301523794, 2],
 [69.63476143421474, 0],
 [125.61448961007643, 2],
 [47.78074926160116, 1],
 [51.19570294468082, 0],
 [75.23961722390672, 2],
 [50.695167422546305, 0],
 [51.19570294468082, 0],
 [46.50806381693394, 1],
 [65.34523701081817, 0],
 [95.17877914745492, 2],
 [83.36666000266533, 0],
 [79.05061669588669, 2],
 [100.74224535913422, 0],
 [85.81375181169973, 0],
 [80.43631020876082, 2],
 [76.02631123499285, 0],
 [108.2081327812286, 2],
 [45.48626166217664, 2],
 [8.06225774829855, 0],
 [77.0, 2],
 [45.48626166217664, 0],
 [34.48187929913333, 1],
 [40.85339643163099, 1],
 [70.9154426059656, 0],
 [29.478805945967352, 1],
 [45.48626166217664, 2],
 [73.78346698278686, 0],
 [53.9351462406472, 2],
 [37.456641600656084, 0],
 [73.21885003194191, 2],
 [51.273774973177076, 1],
 [87.98863562983574, 2],
 [13.490737563232042, 0],
 [33.391615714128, 1],
 [93.73366524360391, 2],
 [50.0199960015992, 0],
 [78.19846545808939, 0],
 [85.14693182963201, 2],
 [72.97259759663213, 0],
 [18.601075237738275, 1],
 [26.77685567799177, 1],
 [105.11898020814318, 0],
 [85.77878525602937, 0],
 [80.2869852466762, 0],
 [40.024992192379, 0],
 [85.85452812752511, 2],
 [86.86771552193599, 2],
 [20.639767440550294, 1],
 [82.35289915965315, 0],
 [83.76753547765387, 2],
 [53.637673327615545, 2],
 [17.378147196982766, 0],
 [43.57751713900185, 0],
 [13.152946437965905, 1],
 [55.66866263886712, 2],
 [40.91454509095757, 0],
 [27.09243436828813, 0],
 [38.3275357934736, 0],
 [77.26577508832743, 0],
 [96.54532614269839, 2],
 [53.79591062525106, 0],
 [86.91375035056306, 2],
 [54.71745608121781, 1],
 [45.39823785126467, 1],
 [36.193922141707716, 1],
 [29.563490998188964, 0],
 [92.02716990106781, 0],
 [79.31582439841371, 2],
 [48.80573736764972, 0],
 [71.50524456289902, 0],
 [60.687725282795036, 0],
 [80.11866199581718, 0],
 [79.06326580656784, 2],
 [84.8174510345601, 2],
 [85.24083528450434, 0],
 [51.176166327695945, 1],
 [38.23610858861032, 1],
 [96.22889378975526, 2],
 [30.215889859476256, 1],
 [34.07345007480164, 0],
 [27.0, 1],
 [60.69596362197407, 0],
 [74.76630257007497, 0],
 [57.879184513951124, 0],
 [24.289915602982237, 1],
 [20.12461179749811, 1],
 [83.36666000266533, 0],
 [83.36666000266533, 0],
 [108.76580344942982, 2],
 [106.53637876331258, 2],
 [83.36666000266533, 0],
 [15.165750888103101, 1],
 [28.106938645110393, 0],
 [104.44615837837216, 2],
 [41.737273509418415, 0],
 [99.72963451251589, 2],
 [85.67963585356792, 0],
 [48.394214530251446, 1],
 [87.20665112249179, 0],
 [23.345235059857504, 2],
 [62.74551776820397, 1],
 [92.09234495874236, 0],
 [16.76305461424021, 1],
 [88.46468221838589, 2],
 [27.477263328068172, 2],
 [98.76740352970711, 2],
 [101.48398888494677, 0],
 [113.50330391667019, 0],
 [40.95119045888654, 1],
 [27.477263328068172, 1],
 [105.09995242624994, 0],
 [34.72751070837067, 0],
 [83.40863264674707, 0],
 [63.92182725798755, 0],
 [101.57263410978372, 2],
 [68.79680225126747, 0],
 [61.587336360651285, 0],
 [28.809720581775867, 0],
 [27.820855486487112, 0],
 [93.6269192059634, 2],
 [88.42510955605314, 0],
 [23.2163735324878, 0],
 [22.22611077089287, 2],
 [108.18964830333815, 2],
 [92.61749294814668, 2],
 [37.66961640367472, 2],
 [62.44197306299666, 2],
 [57.784080852774665, 0],
 [51.254268114957995, 0],
 [76.54410493303844, 2],
 [68.74590896918885, 2],
 [111.35977729862789, 2],
 [112.48999955551605, 2],
 [26.115129714401192, 0],
 [28.372521918222215, 0],
 [91.2414379544733, 2],
 [104.71389592599446, 2],
 [78.71467461661771, 0],
 [87.50999942863673, 0],
 [27.586228448267445, 1],
 [16.431676725154983, 1],
 [108.12030336620407, 2],
 [75.03332592921628, 2],
 [108.12030336620407, 0],
 [75.03332592921628, 0],
 [115.18246394308467, 2],
 [91.92388155425118, 2],
 [17.52141546793523, 0],
 [9.486832980505138, 0],
 [25.25866188063018, 1],
 [25.15949125081825, 1],
 [24.819347291981714, 0],
 [37.8549864614954, 0],
 [41.19465984809196, 0],
 [30.740852297878796, 0],
 [74.3370701601832, 2],
 [71.8679344353238, 2],
 [89.7217922246318, 0],
 [101.21758740456127, 0],
 [21.118712081942874, 0],
 [22.02271554554524, 0],
 [71.17583859709698, 2],
 [73.10950690573696, 2],
 [99.62931295557549, 2],
 [103.07764064044152, 2],
 [101.53324578678651, 2],
 [97.98469268207153, 2],
 [87.25823743349392, 2],
 [82.37718130647589, 2],
 [77.1621668954417, 0],
 [67.74953874381728, 0],
 [28.19574435974337, 1],
 [7.0710678118654755, 1],
 [24.228082879171435, 0],
 [14.142135623730951, 0],
 [28.19574435974337, 1],
 [7.0710678118654755, 1],
 [87.14355971613737, 0],
 [95.60857702110204, 0],
 [28.337254630609507, 1],
 [13.416407864998739, 1],
 [80.31189202104505, 0],
 [67.02238432046416, 0],
 [29.274562336608895, 1],
 [23.874672772626646, 1],
 [83.72574275573791, 0],
 [77.5886589650833, 0],
 [95.25754563287887, 0],
 [87.77812939451375, 0],
 [78.74642849044012, 0],
 [69.13754406977442, 0],
 [77.99358948016176, 0],
 [78.23042886243178, 0],
 [85.98837130682264, 2],
 [71.53320907103218, 2],
 [84.10707461325711, 2],
 [69.1158447825099, 2],
 [23.280893453645632, 1],
 [24.919871588754223, 1],
 [34.49637662132068, 1],
 [30.870698080866262, 1],
 [85.5219270129012, 0],
 [75.69015788066504, 0],
 [86.2670273047588, 2],
 [84.92938243034621, 2],
 [74.60562981437795, 0],
 [73.70888684548153, 0],
 [96.26006440887103, 2],
 [90.33271832508971, 2],
 [75.92759709091287, 0],
 [89.47066558375433, 0],
 [102.00490184299969, 2],
 [91.02197536858887, 2],
 [92.68225288586807, 2],
 [71.05631569396206, 2],
 [54.26785420486054, 0],
 [57.83597496368502, 0],
 [103.99038417084533, 2],
 [82.90355842785037, 2],
 [36.91882988394946, 0],
 [13.416407864998739, 0],
 [25.729360660537214, 1],
 [30.675723300355934, 1],
 [30.495901363953813, 1],
 [13.416407864998739, 1],
 [82.03657720797473, 0],
 [77.0, 0],
 [40.124805295477756, 1],
 [43.46262762420146, 1],
 [24.919871588754223, 1],
 [25.787593916455254, 1],
 [76.08547824650904, 2],
 [77.60154637634484, 2],
 [96.37945839233586, 2],
 [94.09038208021052, 2],
 [78.61297602813418, 0],
 [65.25335240430181, 0],
 [33.481338085566414, 1],
 [39.74921382870358, 1],
 [89.59352655186646, 0],
 [97.27281223445738, 0],
 [101.91172650877817, 2],
 [99.78476837674175, 2],
 [92.233399590387, 2],
 [96.13532129243653, 2],
 [83.12640976248163, 0],
 [91.76055797563569, 0],
 [112.0446339634344, 2],
 [115.56816170554933, 2],
 [59.61543424315552, 0],
 [66.91038783328041, 0],
 [97.05153270299239, 2],
 [90.5869747811461, 2],
 [111.76314240392492, 2],
 [109.77249200050075, 2],
 [35.81898937714463, 1],
 [32.802438933713454, 1],
 [67.96322535018479, 0],
 [77.43384273042376, 0],
 [83.49251463454674, 2],
 [79.79974937304002, 2],
 [89.74408058473828, 0],
 [91.84770002564028, 0],
 [33.03028912982749, 1],
 [30.347981810987037, 1],
 [117.10678887237921, 2],
 [115.56816170554933, 2],
 [106.74268124794318, 2],
 [123.19090875547595, 2],
 [88.51553535961922, 2],
 [92.30926280715278, 2],
 [69.13031173081747, 0],
 [67.08949247087803, 0],
 [100.29456615390487, 2],
 [97.49871794028884, 2],
 [88.89319434017432, 0],
 [94.10632284814874, 0],
 [35.52463933666322, 1],
 [30.265491900843113, 1],
 [90.1443287178955, 2],
 [87.46427842267951, 2],
 [102.22524150130437, 0],
 [97.10303805751909, 0],
 [101.14346246792226, 0],
 [102.70345661174214, 0],
 [93.90420650854784, 0],
 [90.52623929005335, 0],
 [97.25224933131366, 0],
 [92.4824307639024, 0],
 [110.51696702316798, 0],
 [109.78615577567146, 0],
 [89.07300376657341, 0],
 [82.66196223173026, 0],
 [81.51686941977103, 1],
 [84.03570669661795, 1],
 [94.81033698917012, 0],
 [90.17760254076397, 0],
 [106.71925786848408, 2],
 [99.65942002640794, 2],
 [85.38149682454625, 2],
 [85.56284240252891, 2],
 [74.59892760623305, 0],
 [66.49060083951716, 0],
 [81.14801291467339, 0],
 [76.75936424958195, 0],
 [95.4829827770373, 2],
 [92.41753080449618, 2],
 [110.46718969902331, 2],
 [105.11898020814318, 2],
 [101.32620588969075, 0],
 [96.87620966986684, 0],
 [95.38867857350787, 0],
 [93.40770846134703, 0],
 [100.42907945411031, 2],
 [100.61808982484213, 2],
 [91.26883367283708, 2],
 [102.68885041717041, 2],
 [22.494443758403985, 1],
 [28.35489375751565, 1],
 [106.155546251715, 0],
 [97.45768312452333, 0],
 [99.77474630386187, 0],
 [105.41347162483551, 0],
 [38.71692136521188, 1],
 [36.38681079732051, 1],
 [65.3834841531101, 0],
 [63.2771680782255, 0],
 [10.723805294763608, 1]]

In [ ]:
distance.sort()
distance

[[7.0710678118654755, 1],
 [7.0710678118654755, 1],
 [8.06225774829855, 0],
 [8.12403840463596, 1],
 [9.486832980505138, 0],
 [10.723805294763608, 1],
 [11.357816691600547, 0],
 [11.489125293076057, 0],
 [13.152946437965905, 1],
 [13.416407864998739, 0],
 [13.416407864998739, 1],
 [13.416407864998739, 1],
 [13.490737563232042, 0],
 [14.142135623730951, 0],
 [14.89966442575134, 1],
 [15.165750888103101, 1],
 [15.394804318340652, 1],
 [16.30950643030009, 0],
 [16.431676725154983, 1],
 [16.76305461424021, 1],
 [16.881943016134134, 0],
 [17.11724276862369, 1],
 [17.204650534085253, 0],
 [17.378147196982766, 0],
 [17.46424919657298, 0],
 [17.52141546793523, 0],
 [18.33030277982336, 0],
 [18.466185312619388, 0],
 [18.601075237738275, 1],
 [18.601075237738275, 1],
 [18.601075237738275, 1],
 [19.339079605813716, 0],
 [20.12461179749811, 0],
 [20.12461179749811, 1],
 [20.346989949375804, 0],
 [20.639767440550294, 1],
 [21.118712081942874, 0],
 [21.6794833886788, 0],
 [21.6794833886788, 1],
 [22.02271554554524, 0],
 [22.15851980616034, 0],
 [22.22611077089287, 2],
 [22.494443758403985, 1],
 [22.825424421026653, 0],
 [23.08679276123039, 1],
 [23.2163735324878, 0],
 [23.280893453645632, 1],
 [23.345235059857504, 0],
 [23.345235059857504, 2],
 [23.53720459187964, 1],
 [23.706539182259394, 0],
 [23.874672772626646, 1],
 [24.228082879171435, 0],
 [24.289915602982237, 1],
 [24.289915602982237, 1],
 [24.372115213907882, 1],
 [24.779023386727733, 2],
 [24.819347291981714, 0],
 [24.919871588754223, 1],
 [24.919871588754223, 1],
 [25.03996805109783, 0],
 [25.15949125081825, 1],
 [25.25866188063018, 1],
 [25.495097567963924, 1],
 [25.709920264364882, 0],
 [25.729360660537214, 1],
 [25.787593916455254, 1],
 [25.787593916455254, 1],
 [26.115129714401192, 0],
 [26.419689627245813, 1],
 [26.49528259898354, 0],
 [26.551836094703507, 1],
 [26.77685567799177, 1],
 [27.0, 0],
 [27.0, 1],
 [27.09243436828813, 0],
 [27.367864366808018, 1],
 [27.477263328068172, 1],
 [27.477263328068172, 2],
 [27.586228448267445, 1],
 [27.622454633866266, 1],
 [27.820855486487112, 0],
 [28.106938645110393, 0],
 [28.19574435974337, 1],
 [28.19574435974337, 1],
 [28.24889378365107, 1],
 [28.337254630609507, 1],
 [28.35489375751565, 1],
 [28.372521918222215, 0],
 [28.75760768909681, 1],
 [28.809720581775867, 0],
 [28.91366458960192, 0],
 [29.017236257093817, 1],
 [29.068883707497267, 0],
 [29.274562336608895, 1],
 [29.478805945967352, 1],
 [29.563490998188964, 0],
 [29.748949561287034, 1],
 [29.832867780352597, 0],
 [29.9833287011299, 1],
 [30.215889859476256, 1],
 [30.265491900843113, 1],
 [30.347981810987037, 1],
 [30.479501308256342, 0],
 [30.495901363953813, 1],
 [30.675723300355934, 1],
 [30.740852297878796, 0],
 [30.870698080866262, 1],
 [31.448370387032774, 1],
 [31.464265445104548, 0],
 [31.843366656181317, 1],
 [32.4037034920393, 1],
 [32.449961479175904, 0],
 [32.802438933713454, 1],
 [33.03028912982749, 1],
 [33.34666400106613, 0],
 [33.391615714128, 1],
 [33.481338085566414, 1],
 [33.66006535941367, 1],
 [33.97057550292606, 1],
 [34.07345007480164, 0],
 [34.07345007480164, 1],
 [34.14674215792775, 1],
 [34.48187929913333, 1],
 [34.49637662132068, 1],
 [34.68429039204925, 1],
 [34.72751070837067, 0],
 [34.785054261852174, 0],
 [35.34119409414458, 1],
 [35.52463933666322, 1],
 [35.70714214271425, 0],
 [35.81898937714463, 1],
 [35.81898937714463, 1],
 [35.832945734337834, 1],
 [36.138621999185304, 1],
 [36.193922141707716, 1],
 [36.24913792078372, 1],
 [36.38681079732051, 1],
 [36.41428291206625, 0],
 [36.4828726939094, 1],
 [36.51027252705737, 1],
 [36.52396473549935, 1],
 [36.91882988394946, 0],
 [37.013511046643494, 0],
 [37.26929030716845, 1],
 [37.282703764614496, 0],
 [37.456641600656084, 0],
 [37.48332962798263, 1],
 [37.66961640367472, 2],
 [37.68288736283355, 1],
 [37.8549864614954, 0],
 [37.97367509209505, 0],
 [38.23610858861032, 1],
 [38.3275357934736, 0],
 [38.65229618017538, 1],
 [38.71692136521188, 1],
 [38.92300091205713, 1],
 [38.961519477556315, 2],
 [39.370039370059054, 1],
 [39.52214569073901, 1],
 [39.6232255123179, 1],
 [39.74921382870358, 1],
 [39.761790704142086, 2],
 [39.92492955535426, 1],
 [39.97499218261337, 1],
 [40.024992192379, 0],
 [40.124805295477756, 1],
 [40.36087214122113, 0],
 [40.620192023179804, 1],
 [40.85339643163099, 1],
 [40.91454509095757, 0],
 [40.95119045888654, 1],
 [41.19465984809196, 0],
 [41.340053217188775, 0],
 [41.54515615568198, 1],
 [41.737273509418415, 0],
 [41.773197148410844, 1],
 [42.05948168962618, 1],
 [42.8485705712571, 1],
 [43.46262762420146, 1],
 [43.57751713900185, 0],
 [44.15880433163923, 1],
 [45.27692569068709, 1],
 [45.39823785126467, 1],
 [45.48626166217664, 0],
 [45.48626166217664, 2],
 [45.48626166217664, 2],
 [46.50806381693394, 1],
 [46.70117771534247, 0],
 [47.78074926160116, 1],
 [48.394214530251446, 1],
 [48.52834223420371, 0],
 [48.80573736764972, 0],
 [50.0199960015992, 0],
 [50.695167422546305, 0],
 [51.176166327695945, 1],
 [51.19570294468082, 0],
 [51.19570294468082, 0],
 [51.254268114957995, 0],
 [51.273774973177076, 1],
 [51.97114584074513, 2],
 [53.009433122794285, 2],
 [53.08483775994799, 0],
 [53.301031884945715, 0],
 [53.637673327615545, 2],
 [53.79591062525106, 0],
 [53.9351462406472, 2],
 [54.26785420486054, 0],
 [54.71745608121781, 1],
 [55.362442142665635, 1],
 [55.39855593785816, 1],
 [55.66866263886712, 2],
 [56.04462507680822, 0],
 [56.3382640840131, 1],
 [57.784080852774665, 0],
 [57.83597496368502, 0],
 [57.86190456595773, 2],
 [57.879184513951124, 0],
 [58.111960903070546, 2],
 [58.66856057549052, 0],
 [59.61543424315552, 0],
 [59.88321968631947, 1],
 [60.687725282795036, 0],
 [60.69596362197407, 0],
 [61.09009739720506, 0],
 [61.57921727336261, 1],
 [61.587336360651285, 0],
 [62.44197306299666, 2],
 [62.74551776820397, 1],
 [63.2771680782255, 0],
 [63.92182725798755, 0],
 [63.953107821277925, 2],
 [65.25335240430181, 0],
 [65.34523701081817, 0],
 [65.3834841531101, 0],
 [65.62011886609167, 2],
 [66.2872536767062, 2],
 [66.49060083951716, 0],
 [66.91038783328041, 0],
 [67.02238432046416, 0],
 [67.08949247087803, 0],
 [67.74953874381728, 0],
 [67.96322535018479, 0],
 [67.97793759742936, 2],
 [68.4178339323893, 0],
 [68.74590896918885, 2],
 [68.79680225126747, 0],
 [69.1158447825099, 2],
 [69.13031173081747, 0],
 [69.13754406977442, 0],
 [69.63476143421474, 0],
 [69.99285677838846, 0],
 [70.9154426059656, 0],
 [71.05631569396206, 2],
 [71.17583859709698, 2],
 [71.30918594402827, 2],
 [71.50524456289902, 0],
 [71.53320907103218, 2],
 [71.61703707917552, 2],
 [71.8679344353238, 2],
 [72.97259759663213, 0],
 [73.10950690573696, 2],
 [73.21885003194191, 2],
 [73.28028384224504, 0],
 [73.70888684548153, 0],
 [73.78346698278686, 0],
 [74.3370701601832, 2],
 [74.59892760623305, 0],
 [74.60562981437795, 0],
 [74.73285756613352, 0],
 [74.76630257007497, 0],
 [75.03332592921628, 0],
 [75.03332592921628, 2],
 [75.23961722390672, 2],
 [75.56454194925024, 0],
 [75.69015788066504, 0],
 [75.82875444051551, 2],
 [75.92759709091287, 0],
 [76.02631123499285, 0],
 [76.08547824650904, 2],
 [76.54410493303844, 2],
 [76.75936424958195, 0],
 [76.81796664843453, 0],
 [77.0, 0],
 [77.0, 2],
 [77.1621668954417, 0],
 [77.26577508832743, 0],
 [77.26577508832743, 0],
 [77.43384273042376, 0],
 [77.5886589650833, 0],
 [77.60154637634484, 2],
 [77.69813382572325, 0],
 [77.99358948016176, 0],
 [78.19846545808939, 0],
 [78.23042886243178, 0],
 [78.61297602813418, 0],
 [78.71467461661771, 0],
 [78.7210264160726, 0],
 [78.74642849044012, 0],
 [78.80355321938218, 0],
 [78.8986691902975, 0],
 [79.0, 0],
 [79.05061669588669, 2],
 [79.06326580656784, 2],
 [79.30952023559341, 0],
 [79.31582439841371, 2],
 [79.46068210127572, 2],
 [79.79974937304002, 2],
 [80.11866199581718, 0],
 [80.2807573457052, 2],
 [80.2869852466762, 0],
 [80.31189202104505, 0],
 [80.43631020876082, 2],
 [81.14801291467339, 0],
 [81.51686941977103, 1],
 [82.03657720797473, 0],
 [82.35289915965315, 0],
 [82.37718130647589, 2],
 [82.66196223173026, 0],
 [82.90355842785037, 2],
 [83.09031231136396, 0],
 [83.12640976248163, 0],
 [83.36666000266533, 0],
 [83.36666000266533, 0],
 [83.36666000266533, 0],
 [83.36666000266533, 0],
 [83.40863264674707, 0],
 [83.49251463454674, 2],
 [83.72574275573791, 0],
 [83.76753547765387, 2],
 [84.03570669661795, 1],
 [84.10707461325711, 2],
 [84.64632301523794, 2],
 [84.8174510345601, 2],
 [84.92938243034621, 2],
 [85.14693182963201, 2],
 [85.24083528450434, 0],
 [85.38149682454625, 2],
 [85.5219270129012, 0],
 [85.56284240252891, 2],
 [85.58621384311844, 2],
 [85.67963585356792, 0],
 [85.77878525602937, 0],
 [85.81375181169973, 0],
 [85.85452812752511, 2],
 [85.98837130682264, 2],
 [86.2670273047588, 1],
 [86.2670273047588, 2],
 [86.49855490122364, 0],
 [86.86771552193599, 2],
 [86.91375035056306, 2],
 [87.14355971613737, 0],
 [87.20665112249179, 0],
 [87.25823743349392, 2],
 [87.46427842267951, 2],
 [87.50999942863673, 0],
 [87.77812939451375, 0],
 [87.89197915623473, 2],
 [87.98863562983574, 2],
 [88.09653795694811, 0],
 [88.42510955605314, 0],
 [88.46468221838589, 2],
 [88.51553535961922, 2],
 [88.89319434017432, 0],
 [89.07300376657341, 0],
 [89.47066558375433, 0],
 [89.59352655186646, 0],
 [89.65489389877163, 2],
 [89.7217922246318, 0],
 [89.74408058473828, 0],
 [90.1443287178955, 2],
 [90.17760254076397, 0],
 [90.33271832508971, 2],
 [90.52623929005335, 0],
 [90.5869747811461, 2],
 [91.02197536858887, 2],
 [91.2414379544733, 2],
 [91.26883367283708, 2],
 [91.76055797563569, 0],
 [91.84770002564028, 0],
 [91.92388155425118, 2],
 [92.02716990106781, 0],
 [92.07062506576133, 2],
 [92.09234495874236, 0],
 [92.233399590387, 2],
 [92.30926280715278, 2],
 [92.39588735436226, 0],
 [92.41753080449618, 2],
 [92.4824307639024, 0],
 [92.61749294814668, 2],
 [92.68225288586807, 2],
 [93.13968005098579, 2],
 [93.13968005098579, 2],
 [93.40770846134703, 0],
 [93.6269192059634, 2],
 [93.73366524360391, 2],
 [93.90420650854784, 0],
 [93.94147114027967, 2],
 [93.94147114027967, 2],
 [94.09038208021052, 2],
 [94.10632284814874, 0],
 [94.81033698917012, 0],
 [94.98420921395304, 2],
 [95.17877914745492, 2],
 [95.25754563287887, 0],
 [95.38867857350787, 0],
 [95.4829827770373, 2],
 [95.60857702110204, 0],
 [96.13532129243653, 2],
 [96.22889378975526, 2],
 [96.26006440887103, 2],
 [96.37945839233586, 2],
 [96.54532614269839, 2],
 [96.87620966986684, 0],
 [97.05153270299239, 2],
 [97.10303805751909, 0],
 [97.25224933131366, 0],
 [97.27281223445738, 0],
 [97.45768312452333, 0],
 [97.49871794028884, 2],
 [97.98469268207153, 2],
 [98.76740352970711, 2],
 [99.62931295557549, 2],
 [99.65942002640794, 2],
 [99.72963451251589, 2],
 [99.77474630386187, 0],
 [99.78476837674175, 2],
 [100.0499875062461, 2],
 [100.29456615390487, 2],
 [100.42907945411031, 2],
 [100.61808982484213, 2],
 [100.74224535913422, 0],
 [101.14346246792226, 0],
 [101.21758740456127, 0],
 [101.32620588969075, 0],
 [101.48398888494677, 0],
 [101.53324578678651, 2],
 [101.57263410978372, 2],
 [101.91172650877817, 2],
 [102.00490184299969, 2],
 [102.22524150130437, 0],
 [102.68885041717041, 2],
 [102.70345661174214, 0],
 [103.07764064044152, 2],
 [103.75451797391764, 2],
 [103.75451797391764, 2],
 [103.99038417084533, 2],
 [104.44615837837216, 2],
 [104.71389592599446, 2],
 [105.09995242624994, 0],
 [105.11898020814318, 0],
 [105.11898020814318, 2],
 [105.41347162483551, 0],
 [106.155546251715, 0],
 [106.53637876331258, 2],
 [106.71925786848408, 2],
 [106.74268124794318, 2],
 [108.12030336620407, 0],
 [108.12030336620407, 2],
 [108.18964830333815, 2],
 [108.2081327812286, 2],
 [108.76580344942982, 2],
 [109.77249200050075, 2],
 [109.78615577567146, 0],
 [110.46718969902331, 2],
 [110.51696702316798, 0],
 [111.35977729862789, 2],
 [111.76314240392492, 2],
 [112.0446339634344, 2],
 [112.48999955551605, 2],
 [113.50330391667019, 0],
 [114.49890829173874, 0],
 [115.18246394308467, 2],
 [115.56816170554933, 2],
 [115.56816170554933, 2],
 [117.10678887237921, 2],
 [117.32433677630571, 2],
 [123.19090875547595, 2],
 [125.61448961007643, 2]]

In [ ]:
identify=[0 for i in range(len(unique_list))]
for i in range(num_neighbors):
  identify[distance[i][1]]=identify[distance[i][1]]+1

identify

print("The predicted class is: ",unique_list[identify.index(max(identify))])

The predicted class is:  L

KNN Ends

---